insert into tbl_users (isadmin, password) values (true,'pw');
insert into tbl_users (isadmin, password) values (false,'customer');

insert into tbl_users (isadmin, password) values (false,'yf');
insert into tbl_users (isadmin, password) values (true,'ab');
insert into tbl_users (isadmin, password) values (false,'db');
insert into tbl_users (isadmin, password) values (false,'hl');
insert into tbl_users (isadmin, password) values (false,'qy');
insert into tbl_users (isadmin, password) values (false,'sr');
insert into tbl_users (isadmin, password) values (true,'un');
insert into tbl_users (isadmin, password) values (true,'ec');
insert into tbl_users (isadmin, password) values (true,'mi');
insert into tbl_users (isadmin, password) values (true,'ao');
insert into tbl_users (isadmin, password) values (false,'oq');
insert into tbl_users (isadmin, password) values (false,'kg');
insert into tbl_users (isadmin, password) values (true,'sh');
insert into tbl_users (isadmin, password) values (false,'vu');
insert into tbl_users (isadmin, password) values (false,'of');
insert into tbl_users (isadmin, password) values (true,'tb');
insert into tbl_users (isadmin, password) values (true,'mw');
insert into tbl_users (isadmin, password) values (false,'fr');
insert into tbl_users (isadmin, password) values (false,'za');
insert into tbl_users (isadmin, password) values (false,'ag');
insert into tbl_users (isadmin, password) values (false,'lo');
insert into tbl_users (isadmin, password) values (false,'qq');
insert into tbl_users (isadmin, password) values (true,'ei');
insert into tbl_users (isadmin, password) values (false,'ci');
insert into tbl_users (isadmin, password) values (false,'jn');
insert into tbl_users (isadmin, password) values (false,'zn');
insert into tbl_users (isadmin, password) values (false,'zu');
insert into tbl_users (isadmin, password) values (true,'wp');
insert into tbl_users (isadmin, password) values (true,'ri');
insert into tbl_users (isadmin, password) values (true,'xl');
insert into tbl_users (isadmin, password) values (false,'bi');
insert into tbl_users (isadmin, password) values (true,'sr');
insert into tbl_users (isadmin, password) values (true,'sa');
insert into tbl_users (isadmin, password) values (true,'sa');
insert into tbl_users (isadmin, password) values (true,'jm');
insert into tbl_users (isadmin, password) values (false,'vo');
insert into tbl_users (isadmin, password) values (true,'or');
insert into tbl_users (isadmin, password) values (true,'hr');
insert into tbl_users (isadmin, password) values (true,'kh');
insert into tbl_users (isadmin, password) values (true,'pm');
insert into tbl_users (isadmin, password) values (false,'we');
insert into tbl_users (isadmin, password) values (true,'pc');
insert into tbl_users (isadmin, password) values (true,'dv');
insert into tbl_users (isadmin, password) values (false,'xa');
insert into tbl_users (isadmin, password) values (false,'sw');
insert into tbl_users (isadmin, password) values (true,'sw');
insert into tbl_users (isadmin, password) values (false,'zr');
insert into tbl_users (isadmin, password) values (false,'jr');
insert into tbl_users (isadmin, password) values (false,'yk');
insert into tbl_users (isadmin, password) values (false,'uv');
insert into tbl_users (isadmin, password) values (false,'dp');
insert into tbl_users (isadmin, password) values (false,'xt');
insert into tbl_users (isadmin, password) values (false,'oa');
insert into tbl_users (isadmin, password) values (true,'eq');
insert into tbl_users (isadmin, password) values (false,'ml');
insert into tbl_users (isadmin, password) values (false,'nm');
insert into tbl_users (isadmin, password) values (false,'ib');
insert into tbl_users (isadmin, password) values (false,'gk');
insert into tbl_users (isadmin, password) values (true,'xb');
insert into tbl_users (isadmin, password) values (true,'uh');
insert into tbl_users (isadmin, password) values (true,'ia');
insert into tbl_users (isadmin, password) values (false,'mu');
insert into tbl_users (isadmin, password) values (false,'rr');
insert into tbl_users (isadmin, password) values (true,'hw');
insert into tbl_users (isadmin, password) values (false,'ui');
insert into tbl_users (isadmin, password) values (false,'kf');
insert into tbl_users (isadmin, password) values (false,'ay');
insert into tbl_users (isadmin, password) values (true,'en');
insert into tbl_users (isadmin, password) values (false,'ia');
insert into tbl_users (isadmin, password) values (false,'kt');
insert into tbl_users (isadmin, password) values (false,'mv');
insert into tbl_users (isadmin, password) values (false,'op');
insert into tbl_users (isadmin, password) values (false,'gt');
insert into tbl_users (isadmin, password) values (true,'hp');
insert into tbl_users (isadmin, password) values (true,'oo');
insert into tbl_users (isadmin, password) values (false,'ft');
insert into tbl_users (isadmin, password) values (false,'of');
insert into tbl_users (isadmin, password) values (true,'bq');
insert into tbl_users (isadmin, password) values (true,'vj');
insert into tbl_users (isadmin, password) values (true,'nn');
insert into tbl_users (isadmin, password) values (true,'cp');
insert into tbl_users (isadmin, password) values (true,'vc');
insert into tbl_users (isadmin, password) values (true,'ka');
insert into tbl_users (isadmin, password) values (false,'bd');
insert into tbl_users (isadmin, password) values (true,'mu');
insert into tbl_users (isadmin, password) values (false,'zj');
insert into tbl_users (isadmin, password) values (false,'iq');
insert into tbl_users (isadmin, password) values (false,'mg');
insert into tbl_users (isadmin, password) values (false,'hf');
insert into tbl_users (isadmin, password) values (false,'sl');
insert into tbl_users (isadmin, password) values (false,'qk');
insert into tbl_users (isadmin, password) values (true,'lc');
insert into tbl_users (isadmin, password) values (false,'xd');
insert into tbl_users (isadmin, password) values (false,'za');
insert into tbl_users (isadmin, password) values (true,'ka');
insert into tbl_users (isadmin, password) values (false,'nu');
insert into tbl_users (isadmin, password) values (true,'nv');
insert into tbl_users (isadmin, password) values (true,'oz');
insert into tbl_users (isadmin, password) values (true,'he');
insert into tbl_users (isadmin, password) values (true,'nk');


--import java.util.Random;
--public class Make {
--   private static final int NUM_THINGOS = 100;
--   public static void main (String[] args) {
--      Random rng = new Random();
--      boolean tf;
--      String pw;
--      for (int i=0; i < NUM_THINGOS; i++) {
--         tf = rng.nextBoolean();
--         pw = "";
--         pw += (char) ('a' + rng.nextInt(26));
--         pw += (char) ('a' + rng.nextInt(26));
--         System.out.println("insert into tbl_users (isadmin, password) values (" + tf +",\'"+pw+"\');");
--      }
--
--   }
--}
